version: '3'
services:
  app:
    build: ./registro
    volumes:
      - './registro:/urs/app'
    ports:
    - '3000:3000'
    restart: always
  bd:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: banco
    environment:
      MYSQL_DATABASE: 'bancoADS'
      MYSQL_ROOT_PASSWORD: '1234'
    volumes:
      - ./db:/var/lib/mysql
      - ./registro/db/script.sql:/docker-entrypoint-initdb.d/script_bd.sql:ro
    expose:
      - '3306'
    ports:
     - '3306:3306'
