CREATE DATABASE IF NOT EXISTS bancoADS;
USE bancoADS;

CREATE TABLE IF NOT EXISTS alunos (
    id INT(11) AUTO_INCREMENT,
    nome VARCHAR(255),
    email VARCHAR(255),
    curso VARCHAR(255)
);

INSERT INTO alunos VALUE(1, 'WENDEL', 'WENDEL@GMAIL.COM', 'ADS')